### PR TITLE
Sekachev/render table

### LINKED ISSUE #10: Render table

### PR DESCRIPTION
**Pull request by cement-hools**
Added a table render from the dataset

### CODE REVIEW

**Comment by Thykof** [comment]
Hi @cement-hools thanks for the contribution. Is everything ready to review?

**Comment by cement-hools** [comment]
> Hi @cement-hools thanks for the contribution. Is everything ready to review?
Yes, of course

**Comment by cement-hools** [comment]
@Thykof 

Is something wrong? Why don't you do a review?

**Comment by Thykof** [comment]
> @Thykof
> 
> Is something wrong? Why don't you do a review?

Hi, simply because I couldn't find time.

**Comment by Thykof** [comment]
I published the new version https://pypi.org/project/template-pptx-jinja/

**Pull request merged**
